# This file is used to run the sys-design-diagram service in a container
# usage: docker compose up --build
# The output will be saved in the sdd-output folder in the current directory
# test-data folder contains the design files in puml and python format(diagrams library)
services:
  sdd-process-all:
    image: sdd-test:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./sdd-outputs/sdd-all:/output
      - ./tests-data:/designs:ro
    command: ["process-all", "-d", "/designs", "-o", "/output"]

  sdd-plantuml:
    image: sdd-test:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./sdd-outputs/sdd-plantuml:/output
      - ./tests-data:/designs:ro
    command: ["plantuml", "-d", "/designs", "-o", "/output"]

  sdd-diagrams:
    image: sdd-test:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./sdd-outputs/sdd-diagrams:/output
      - ./tests-data:/designs:ro
    command: ["diagrams", "-d", "/designs", "-o", "/output"]

  sdd-mermaids:
    image: sdd-local:latest
    build:
      context: .
      dockerfile: ./Dockerfile_local
    volumes:
      - ./sdd-outputs/sdd-mermaids:/output
      - ./tests-data:/designs:ro
    shm_size: 256m
    command: ["mermaid", "-d", "/designs", "-o", "/output"]

  sdd-build-locally:
    image: sdd-local:latest
    build:
      context: .
      dockerfile: ./Dockerfile_local
    volumes:
      - ./sdd-local-outputs:/output
      - ./tests-data:/designs:ro
    command: ["process-all", "-d", "/designs", "-o", "/output"]

networks: {}
